"""wallet

Revision ID: 72ed3590f027
Revises: 
Create Date: 2025-04-14 20:06:45.306447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ed3590f027'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.Column('energy', sa.String(), nullable=False),
    sa.Column('bandwidth', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
